const SUPABASE_URL = "https://msfbyneidkfhmofnoupg.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zZmJ5bmVpZGtmaG1vZm5vdXBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU4ODgwMjQsImV4cCI6MjEwMTQ2NDAyNH0.Hvwtw18XzzxsTjOFcDi7OuNXAtIQcTWgHeFo-0_Ydf0";

const sb = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
